### ISSUE TITLE
2차 안건

### ISSUE THREAD

**Issue by GGURRU** [liArizenil/Dalix-Liberation#6]
- [ ]  새로운 후방 교란 추가

- [x]  대도시 전략 건물 추가 [페레스만 시범적으로 진행]

- [ ] 무전망 스크립트 단축키 추가

- [x] 탄약 리팩 스크립트 추가

- [x] 오레오카스트로 대도시 승급

- [ ] 통제권 상실 AI 제어 기능 추가

- [ ] 보병 분대장의 항공망 접속 권한 추가

- [ ] 담넘기 스크립트 추가

- [x] 오토런 키를 - 와 = 로 변경

**Comment by liArizenil** [comment]
Break 업데이트로 병합
